### ISSUE TITLE
Is the final goal of the project to reflash the controller's firmware or just redirect input?

### ISSUE THREAD

**Issue by Two-Tone** [ynsta/steamcontroller#1]
Sorry for cluttering up the issue tracker with this, I didn't know of any other place to ask this question.

A couple months ago there was talk from some Steam Controller devs that had mentioned that Steam reflashes the firmware every time the bindings are changed to not have any of the inherent latency that comes with software based input redirection.

Is the plan to eventually be able to do the same?

**Comment by ynsta** [comment]
Steam Controller no longer reflash the firmware, it uses uinput redirection like my driver (on Linux don't know the equivalent mechanism on Windows). I think they changed to permit very simple remapping at live, even while playing. It's very usefull when you fine tune you settings.

With firmware flashing there is a lot of potential issue, and also a delay to reconnect the gamepad that should have required to restart the game.

The latency might be increased but I think that this time would be be very very small compared to human reaction time.

If I have some time I'll perform some measurement (maybe with an oscilloscope) of the time between the usb message reception and the generated event received by a user application.
