### ISSUE TITLE
init scripts

### ISSUE THREAD

**Issue by johnjelinek** [ynsta/steamcontroller#20]
Can you please add init.d or systemd scripts so the daemon will start on boot?

**Comment by ynsta** [comment]
As it is very distribution specific I think it should be done by the
distribution packager. But I'll add a sample systemd script.

**Comment by johnjelinek** [comment]
I guess you could steal this systemd script: https://github.com/lrusak/lrusak-openelec-addons/blob/master/addons/service/driver/steamcontroller/source/systemd/service.driver.steamcontroller.service

**Comment by johnjelinek** [comment]
This is what I ended up going with, it works pretty good:
```
[Unit]
Description=SteamController Userland driver

[Service]
Type=forking
PIDFile=/tmp/steamcontroller.pid
ExecStart=/usr/local/bin/sc-xbox.py start
ExecReload=/usr/local/bin/sc-xbox.py restart
ExecStop=/usr/local/bin/sc-xbox.py stop

[Install]
WantedBy=multi-user.target
```
