### ISSUE TITLE
Typos, maybe not

### ISSUE THREAD

**Issue by nephitejnf** [ynsta/steamcontroller#23]
I was going through documenting stuff to make it easier on me to use this as an API and I ran across something that looks like a typo to me, based on context. On line 218 in events.py, is has this:
`click = SCButtons.LPAD`
but I think it would be this, being as it was in a right pad context: 
`click = SCButtons.RPAD`

**Comment by ynsta** [comment]
Thank you type corrected in commit dc9f278
