### ISSUE TITLE
Test to see if controller is connected

### ISSUE THREAD

**Issue by bmurphy1976** [ynsta/steamcontroller#27]
Is there a way I can test to see if the controller is powered on and connected (not just the dongle)?  I'd like to write a daemon that automatically starts emulation station when the controller is powered on and terminates it when the controller is powered off.

**Comment by cvuchener** [comment]
The receiver sends reports when a device is connected or disconnected. You can also ask the receiver to resend the current state (0xb4) for initialisation. 

See my driver: https://github.com/cvuchener/input-scripts/blob/master/src/daemon/steamcontroller/SteamControllerReceiver.cpp

At line 95 for sending the message asking to resend the connection status. And see parseReport at line 159 for parsing the report (type 0x03 for connection events, 0x01 is for inputs).

**Comment by Atterratio** [comment]
Hey! How about daemon that use bash not js?

**Comment by cvuchener** [comment]
This is off-topic, but what would you do with that? Handling input events by running bash scripts does not seem reasonable to me.

**Comment by Atterratio** [comment]
I want simple run some bash command like want TS, but don't want some js engine what non in repos.

**Comment by cvuchener** [comment]
Then, you could try this driver: https://gitlab.com/dennis-hamester/scd. I did not test it myself, but I understand it has a proper hot plug support.
