### ISSUE TITLE
ImportError: No module named usb1

### ISSUE THREAD

**Issue by SilasMortimer** [ynsta/steamcontroller#31]
I'm getting the following error message when I try to run either script (except the other one says /usr/bin/sc-desktop.py instead):

`Traceback (most recent call last):
  File "/usr/bin/sc-xbox.py", line 27, in <module>
    from steamcontroller import \
  File "/usr/lib64/python2.7/site-packages/steamcontroller/__init__.py", line 21, in <module>
    import usb1
ImportError: No module named usb1`

After this, it is, of course, not working.

**Comment by akien-mga** [comment]
As mentioned in the README.md, you need to install libusb1: https://github.com/vpelletier/python-libusb1
You can grab it via pypi too:
```
# pip install libusb1
```
