### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by the100guy** [ynsta/steamcontroller#33]
eh... help? I'm new-ish to linux, so naturally I have no idea what to do or what this means.
can anyone help me out here?

When I type "sc-xbox.py enable" : 

 File "/usr/local/bin/sc-xbox.py", line 27, in <module>
    from steamcontroller import \
  File "/usr/local/lib/python2.7/dist-packages/steamcontroller/__init__.py", line 24, in <module>
    from enum import IntEnum
ImportError: No module named enum

**Comment by SolarLune** [comment]
What version of Python do you have? I'm guessing you might be using an older version, which doesn't work because [enum is a module that was added in Python v3.4](https://docs.python.org/3/library/enum.html).

**Comment by ynsta** [comment]
As stated in the readme for python for python 2.7 you must install python enum backport:

pip install enum34

This dependency should be added in setup.py if python version < 3.4.

**Comment by the100guy** [comment]
yeah thanks, after looking up and down the page I saw that it was a required thing. Thanks though!
