### ISSUE TITLE
Reading outputs directly

### ISSUE THREAD

**Issue by nothinn** [ynsta/steamcontroller#37]
Hello, i am trying to make the steam controller work on my raspberry pi 2, in order to use it for an external game. Therefore, i need to be able to read the different buttons in a program, that only needs to control the gpio's on the board.  So, i just need to know how to grab the data sent from the controller, just like the sc-dump does, however, i need it stored in some variables that i can interact with. I have a hard time finding the functions to call, in order to do this, as my main language is not python. Any help appreciated, as this could be used for many things, including controlling RC-cars, drones and other things from the gpio.

**Comment by nothinn** [comment]
Found a way, where i configured in the sc-dump file, though it is a workaround. This is how i made it:
```
def dump(_, sci):
    if sci[5] < 0:
        GPIO.output(2,True)
    else:
        GPIO.output(2,False)
```
I would still like to have a small description, in order to make a correct function that does not just hack another.

**Comment by ynsta** [comment]
Maybe you could use the callback API as in sc-callbacks.py.

**Comment by nothinn** [comment]
I can't seem to find out how to use the callbacks correctly.. I am always left using the pre-made callback functions, where i just read the sci-data, as in my example above. If you have the time to write the lines of code needed to attach a button to a variable in python, it would be much appreciated. Or perhaps explain how the sci in the dump funtion works, in order to use it with  other projects. 
p.s.
I love the work you have done for using the steam controller on linux systems, i am surely going to be using it for many of my projects. If in no other ways, by decoding the sci output.

**Comment by ynsta** [comment]
The sci is a tuple built from usb data decoded with struct in __init__.py
SteamControllerInput._make(struct.unpack('<' + ''.join(_FORMATS), data))

_FORMATS are constructed from STEAM_CONTROLER_FORMAT also in __init__.py.

using callbacks as in sc-callbakcs.py you should use something like this:
```
import sys

from steamcontroller import SteamController, SCButtons
from steamcontroller.events import EventMapper, Pos
from steamcontroller.uinput import Keys

def btnAPressedCallback(evm, btn, pressed):
    GPIO.output(2, pressed)

def exitCallback(evm, btn, pressed):
    if not pressed:
        sys.exit()

def evminit():
    evm = EventMapper()
    evm.setButtonCallback(SCButtons.A, btnAPressedCallback)
    evm.setButtonCallback(SCButtons.STEAM, exitCallback)
    return evm

if __name__ == '__main__':
    evm = evminit()
    sc = SteamController(callback=evm.process)
    sc.run()
```
