### ISSUE TITLE
Repo key expired.

### ISSUE THREAD

**Issue by salamanderrake** [ynsta/steamcontroller#46]
Updating from your repo, 

`sudo apt-get update`

causes this message.

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1480161281
W: Failed to fetch http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1480161281
`

**Comment by ynsta** [comment]
Hi,

It's not me behind this repository you should contact @kozec.

Regards,

**Comment by kozec** [comment]
Yep, that's my name :)

@salamanderrake , here:
https://github.com/kozec/sc-controller/issues/121#issuecomment-263983124

Correct repository and most likely solution as well.

**Comment by salamanderrake** [comment]
Sorry, I picked the first sc-controller repo I found, should have been paying attention.
