### ISSUE TITLE
input on right touchpad is recognized incorrectly

### ISSUE THREAD

**Issue by majewsky** [ynsta/steamcontroller#5]
I installed the latest commit (074ccf2) on my Arch desktop using the PKGBUILD from AUR, and took the XBox controller emulation for a spin in PCSX2. Most of the buttons and axes are working great, except for the right touchpad. Both of its axes are recognized as "AXIS1", which apparently is the vertical axis on the left analog stick, when it should probably be mapped to both axes of the right analog stick. To witness, here's a screenshot of the input configuration dialog for PCSX2 (note the various "jAxis 0" entries in the list view):

![screen20](https://cloud.githubusercontent.com/assets/24696/11447740/a4b68eda-954b-11e5-8590-9356ad44680e.png)

**Comment by markubiak** [comment]
I can confirm that the latest commit from the AUR has the right touchpad assigned to the same axes as the left analog stick.

**Comment by ynsta** [comment]
Thanks for the report.

It should now be corrected.

Regards.
