### ISSUE TITLE
sc-dump.py errors out when using controller wired

### ISSUE THREAD

**Issue by AcouBass** [ynsta/steamcontroller#7]
I've installed the latest git code both through he Arch Linux AUR package and manually using the setup.py install method - at first I thought the software wasn't working at all, however I discovered that it works perfectly when I use my controller wirelessly.  

I generally use my controller on the wire, as I sit fairly close to my PC anyway so I don't need wireless, and I'm a bit lazy when it comes to batteries.  

When I run sc-dump.py, I get the error:  

> SteamControler Device not found
> Bye

And the rest of the sc- scripts don't work at all.  

Again, I'd like to stress that this is only a problem when I'm plugged in using the USB cable (Which works just fine in Steam BPM). Without running any sc-scripts at all, my controller still gets picked up as a mouse on the right touchpad and various buttons on the rest.

**Comment by ynsta** [comment]
Hi,

It should now be fixed.

Regards,

**Comment by AcouBass** [comment]
Confirmed and working, thanks a lot :+1:
